### ISSUE TITLE
Binary files committed in git.

### ISSUE THREAD

**Issue by ChenPi11** [xiaoyi1212/CrashPowerDOS#4]
`crashpowerdos-x86-nodesktop-rebuild-0.0.2.iso` and `cpos.qcow2` was committed in git. This is not a good practice,
because when the developer modifies it, the total size of the `.git` directory will grow quickly.

I think you can upload it in releases assets in GitHub.

**Comment by xiaoyi1212** [comment]
For your issues, It was an oversight on my part. But I rarely worked on this project anymore, so I didn't update it
